import { WMOWeatherInfo } from '../types/weather';

export const WMO_CODES: Record<number, WMOWeatherInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Bright and clear skies with maximum sunshine',
    iconName: 'Sun',
    category: 'clear',
    bgGradient: 'from-amber-500/10 via-sky-500/10 to-indigo-500/10',
    accentColor: 'text-amber-500',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly sunny with faint or scattered clouds',
    iconName: 'SunMedium',
    category: 'clear',
    bgGradient: 'from-amber-400/10 via-sky-400/10 to-blue-500/10',
    accentColor: 'text-amber-500',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Mix of sunshine and friendly cloud formations',
    iconName: 'CloudSun',
    category: 'cloudy',
    bgGradient: 'from-sky-500/10 via-slate-400/10 to-indigo-500/10',
    accentColor: 'text-sky-500',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Dense cloud blanket covering the sky',
    iconName: 'Cloud',
    category: 'cloudy',
    bgGradient: 'from-slate-500/10 via-zinc-500/10 to-slate-700/10',
    accentColor: 'text-slate-400',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Low visibility due to dense misty fog layer',
    iconName: 'CloudFog',
    category: 'fog',
    bgGradient: 'from-zinc-400/10 via-slate-500/10 to-stone-600/10',
    accentColor: 'text-zinc-400',
  },
  48: {
    code: 48,
    label: 'Rime Fog',
    description: 'Freezing fog depositing delicate frost crystals',
    iconName: 'CloudFog',
    category: 'fog',
    bgGradient: 'from-slate-300/10 via-cyan-500/10 to-zinc-600/10',
    accentColor: 'text-cyan-400',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Gentle mist-like rain sprinkles',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    bgGradient: 'from-cyan-500/10 via-sky-500/10 to-slate-600/10',
    accentColor: 'text-cyan-500',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady light rain droplets falling continuously',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    bgGradient: 'from-cyan-600/10 via-blue-500/10 to-slate-600/10',
    accentColor: 'text-cyan-500',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy damp drizzle dampening outdoor surfaces',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    bgGradient: 'from-blue-600/10 via-cyan-600/10 to-slate-700/10',
    accentColor: 'text-blue-500',
  },
  56: {
    code: 56,
    label: 'Freezing Drizzle',
    description: 'Light freezing drizzle forming icy glaze',
    iconName: 'CloudHail',
    category: 'drizzle',
    bgGradient: 'from-teal-500/10 via-cyan-600/10 to-slate-700/10',
    accentColor: 'text-teal-400',
  },
  57: {
    code: 57,
    label: 'Heavy Freezing Drizzle',
    description: 'Dense freezing drizzle coating roads with thin ice',
    iconName: 'CloudHail',
    category: 'drizzle',
    bgGradient: 'from-teal-600/10 via-slate-600/10 to-blue-800/10',
    accentColor: 'text-teal-300',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light rain showers falling steadily',
    iconName: 'CloudRain',
    category: 'rain',
    bgGradient: 'from-blue-500/10 via-sky-600/10 to-slate-700/10',
    accentColor: 'text-blue-500',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady rainfall requiring an umbrella',
    iconName: 'CloudRain',
    category: 'rain',
    bgGradient: 'from-blue-600/10 via-indigo-600/10 to-slate-800/10',
    accentColor: 'text-blue-400',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Pouring downpours with significant accumulation',
    iconName: 'CloudRainWind',
    category: 'rain',
    bgGradient: 'from-blue-700/10 via-indigo-800/10 to-slate-900/10',
    accentColor: 'text-indigo-400',
  },
  66: {
    code: 66,
    label: 'Freezing Rain',
    description: 'Rain freezing instantly upon contact with cold surfaces',
    iconName: 'CloudHail',
    category: 'rain',
    bgGradient: 'from-cyan-700/10 via-blue-800/10 to-slate-900/10',
    accentColor: 'text-cyan-300',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Severe freezing rain creating icy slick conditions',
    iconName: 'CloudHail',
    category: 'rain',
    bgGradient: 'from-teal-800/10 via-cyan-900/10 to-slate-950/10',
    accentColor: 'text-teal-300',
  },
  71: {
    code: 71,
    label: 'Slight Snow',
    description: 'Gentle snowflakes drifting softly',
    iconName: 'CloudSnow',
    category: 'snow',
    bgGradient: 'from-sky-200/20 via-indigo-200/20 to-slate-400/20',
    accentColor: 'text-sky-300',
  },
  73: {
    code: 73,
    label: 'Moderate Snow',
    description: 'Steady snowfall accumulating on ground',
    iconName: 'CloudSnow',
    category: 'snow',
    bgGradient: 'from-sky-300/20 via-blue-300/20 to-slate-500/20',
    accentColor: 'text-sky-200',
  },
  75: {
    code: 75,
    label: 'Heavy Snow',
    description: 'Dense blizzard-like snowfall with heavy buildup',
    iconName: 'Snowflake',
    category: 'snow',
    bgGradient: 'from-blue-200/20 via-indigo-300/20 to-slate-600/20',
    accentColor: 'text-blue-200',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Tiny crisp ice grains falling lightly',
    iconName: 'Snowflake',
    category: 'snow',
    bgGradient: 'from-sky-300/20 via-slate-400/20 to-zinc-500/20',
    accentColor: 'text-sky-300',
  },
  80: {
    code: 80,
    label: 'Light Showers',
    description: 'Passing brief rain showers',
    iconName: 'CloudRain',
    category: 'rain',
    bgGradient: 'from-sky-500/10 via-blue-600/10 to-slate-700/10',
    accentColor: 'text-sky-400',
  },
  81: {
    code: 81,
    label: 'Moderate Showers',
    description: 'Brisk intermittent rain showers',
    iconName: 'CloudRain',
    category: 'rain',
    bgGradient: 'from-blue-600/10 via-sky-700/10 to-slate-800/10',
    accentColor: 'text-blue-400',
  },
  82: {
    code: 82,
    label: 'Violent Showers',
    description: 'Heavy torrential shower bursts with strong gusts',
    iconName: 'CloudRainWind',
    category: 'rain',
    bgGradient: 'from-indigo-800/10 via-blue-900/10 to-slate-950/10',
    accentColor: 'text-indigo-400',
  },
  85: {
    code: 85,
    label: 'Snow Showers',
    description: 'Intermittent snow flurries',
    iconName: 'CloudSnow',
    category: 'snow',
    bgGradient: 'from-sky-300/20 via-blue-400/20 to-slate-600/20',
    accentColor: 'text-sky-300',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense snow shower flurries with low visibility',
    iconName: 'Snowflake',
    category: 'snow',
    bgGradient: 'from-blue-400/20 via-indigo-500/20 to-slate-800/20',
    accentColor: 'text-blue-200',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Electric storm with lightning flashes and thunder rolls',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    bgGradient: 'from-purple-900/15 via-slate-900/15 to-indigo-950/15',
    accentColor: 'text-amber-400',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    description: 'Thunderstorm accompanied by light hail pellets',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    bgGradient: 'from-purple-950/15 via-blue-950/15 to-slate-900/15',
    accentColor: 'text-amber-300',
  },
  99: {
    code: 99,
    label: 'Heavy Hailstorm',
    description: 'Severe thunderstorm with large damaging hail stones',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    bgGradient: 'from-violet-950/20 via-indigo-950/20 to-slate-950/20',
    accentColor: 'text-purple-400',
  },
};

export function getWMOInfo(code: number): WMOWeatherInfo {
  return WMO_CODES[code] || {
    code,
    label: 'Unknown Weather',
    description: 'Conditions variable or unclassified',
    iconName: 'Cloud',
    category: 'cloudy',
    bgGradient: 'from-slate-500/10 via-gray-500/10 to-slate-700/10',
    accentColor: 'text-slate-400',
  };
}
